server:
  port: 8888
  servlet:
    context-path: /demo

#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #如果使用高版本驱动 则添加cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.30.5.12:31289/sims-test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: schoolBD
    password: Fbhu0359
    druid:
      initial-size: 5
      filter:
        stat:
          log-slow-sql: true
      min-idle: 5
      max-active: 30
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL

#Spring整合Mybatis
mybatis-plus:
  #导入映射文件(指定映射文件的路径)
  mapper-locations: classpath:mapper/*.xml
  #定义别名包
  typeAliasesPackage:

